In [2]:
import pandas as pd

In [3]:
covid_df = pd.read_csv("covid_italy_250_days.csv")

In [4]:
type(covid_df)

pandas.DataFrame

In [5]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[250 rows x 4 columns]

In [6]:
covid_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        250 non-null    str
 1   new_cases   250 non-null    float64
 2   new_deaths  250 non-null    float64
 3   new_tests   250 non-null    float64
dtypes: float64(3), str(1)
memory usage: 7.9 KB

In [7]:
covid_df.describe()

          new_cases  new_deaths     new_tests
count    250.000000  250.000000     250.00000
mean    7411.428000  190.796000   98192.61200
std    11025.459118  248.686417   61905.97724
min      114.000000  -31.000000  -47510.00000
25%      340.000000   12.250000   52552.25000
50%     1399.000000   54.000000   72065.50000
75%    13177.500000  329.000000  142907.75000
max    40902.000000  993.000000  254908.00000

In [9]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

In [10]:
covid_df.shape

(250, 4)

In [11]:
covid_df['new_cases']

0       2256.0
1       2729.0
2       3370.0
3       2646.0
4       3021.0
        ...
245    10872.0
246    13318.0
247    14522.0
248    18040.0
249    19037.0
Name: new_cases, Length: 250, dtype: float64

In [12]:
covid_df['new_cases'][243]

np.float64(16308.0)

In [19]:
covid_df.at[246, 'new_cases']

np.float64(13318.0)

In [14]:
covid_df.new_cases

0       2256.0
1       2729.0
2       3370.0
3       2646.0
4       3021.0
        ...
245    10872.0
246    13318.0
247    14522.0
248    18040.0
249    19037.0
Name: new_cases, Length: 250, dtype: float64

In [21]:
covid_df[['new_cases', 'date']]

     new_cases        date
0       2256.0  2020-04-21
1       2729.0  2020-04-22
2       3370.0  2020-04-23
3       2646.0  2020-04-24
4       3021.0  2020-04-25
..         ...         ...
245    10872.0  2020-12-22
246    13318.0  2020-12-23
247    14522.0  2020-12-24
248    18040.0  2020-12-25
249    19037.0  2020-12-26

[250 rows x 2 columns]

In [22]:
covid_df_copy = covid_df.copy()

In [23]:
covid_df.loc[243]

date          2020-12-20
new_cases        16308.0
new_deaths         553.0
new_tests       176185.0
Name: 243, dtype: object

In [27]:
covid_df.head(3)

         date  new_cases  new_deaths  new_tests
0  2020-04-21     2256.0       454.0    41483.0
1  2020-04-22     2729.0       534.0    52126.0
2  2020-04-23     3370.0       437.0    63101.0

In [28]:
covid_df.new_tests.first_valid_index() # finding the first non empty

0

In [29]:
covid_df.loc[108:113]

           date  new_cases  new_deaths  new_tests
108  2020-08-07      402.0         6.0    58673.0
109  2020-08-08      552.0         3.0    59196.0
110  2020-08-09      347.0        13.0    53298.0
111  2020-08-10      463.0         2.0    37637.0
112  2020-08-11      259.0         4.0    26432.0
113  2020-08-12      412.0         6.0    40642.0

In [30]:
covid_df.sample(10)

           date  new_cases  new_deaths  new_tests
33   2020-05-24      669.0       119.0    72410.0
93   2020-07-23      282.0         9.0    49318.0
47   2020-06-07      270.0        72.0    72485.0
75   2020-07-05      235.0        21.0    52011.0
28   2020-05-19      451.0        99.0    36406.0
146  2020-09-14     1458.0         7.0    72143.0
40   2020-05-31      416.0       111.0    69342.0
219  2020-11-26    25853.0       722.0   230007.0
32   2020-05-23      652.0       130.0    75380.0
194  2020-11-01    31758.0       297.0   215886.0

In [32]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()
print(total_cases)
print(total_deaths)

1852857.0
47699.0

In [34]:
death_rate = total_deaths / total_cases
print(death_rate)

0.025743486950153195

In [37]:
initial_tests = 935310
total_tests = initial_tests + covid_df.new_tests.sum()

In [38]:
total_tests

np.float64(25483463.0)

In [40]:
positive_rate = total_cases / total_tests
print(positive_rate)

0.07270821081106599

In [41]:
high_new_cases = covid_df.new_cases > 1000

In [42]:
high_new_cases

0      True
1      True
2      True
3      True
4      True
       ...
245    True
246    True
247    True
248    True
249    True
Name: new_cases, Length: 250, dtype: bool

In [43]:
covid_df[high_new_cases]

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[143 rows x 4 columns]

In [44]:
high_cases_df = covid_df[covid_df.new_cases > 1000]

In [46]:
high_cases_df

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[143 rows x 4 columns]

In [47]:
from IPython.display import display
with pd.option_context('display.max_rows', 100):
    display(covid_df[covid_df.new_cases > 1000])

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[143 rows x 4 columns]

In [48]:
covid_df['positive_rate'] = covid_df.new_cases / covid_df.new_tests

In [51]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[250 rows x 4 columns]

In [50]:
covid_df.drop(columns = ['positive_rate'], inplace=True)

In [52]:
covid_df.sort_values('new_cases', ascending=False).head(10)

           date  new_cases  new_deaths  new_tests
207  2020-11-14    40902.0       550.0   254908.0
201  2020-11-08    39811.0       425.0   231673.0
206  2020-11-13    37978.0       636.0   234672.0
200  2020-11-07    37809.0       446.0   234245.0
208  2020-11-15    37255.0       544.0   227695.0
214  2020-11-21    37242.0       699.0   238077.0
213  2020-11-20    36176.0       653.0   250186.0
204  2020-11-11    35098.0       580.0   217758.0
215  2020-11-22    34767.0       692.0   237225.0
199  2020-11-06    34505.0       445.0   219884.0

In [53]:
covid_df.sort_values('new_deaths', ascending=False).head(10)

           date  new_cases  new_deaths  new_tests
227  2020-12-04    23225.0       993.0   220047.0
234  2020-12-11    16999.0       887.0   171586.0
218  2020-11-25    23232.0       853.0   188659.0
239  2020-12-16    14844.0       846.0   164431.0
221  2020-11-28    28352.0       827.0   222803.0
220  2020-11-27    29003.0       822.0   232711.0
228  2020-12-05    24099.0       814.0   212741.0
225  2020-12-02    19350.0       785.0   182100.0
235  2020-12-12    18727.0       761.0   190416.0
212  2020-11-19    34282.0       753.0   234834.0

In [54]:
covid_df['date'] = pd.to_datetime(covid_df.date)

In [55]:
covid_df['date']

0     2020-04-21
1     2020-04-22
2     2020-04-23
3     2020-04-24
4     2020-04-25
         ...
245   2020-12-22
246   2020-12-23
247   2020-12-24
248   2020-12-25
249   2020-12-26
Name: date, Length: 250, dtype: datetime64[us]

In [56]:
covid_df['year'] = pd.DatetimeIndex(covid_df.date).year
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday

In [57]:
covid_df

          date  new_cases  new_deaths  new_tests  year  month  day  weekday
0   2020-04-21     2256.0       454.0    41483.0  2020      4   21        1
1   2020-04-22     2729.0       534.0    52126.0  2020      4   22        2
2   2020-04-23     3370.0       437.0    63101.0  2020      4   23        3
3   2020-04-24     2646.0       464.0    66658.0  2020      4   24        4
4   2020-04-25     3021.0       420.0    62447.0  2020      4   25        5
..         ...        ...         ...        ...   ...    ...  ...      ...
245 2020-12-22    10872.0       415.0    87889.0  2020     12   22        1
246 2020-12-23    13318.0       628.0   157705.0  2020     12   23        2
247 2020-12-24    14522.0       553.0   183864.0  2020     12   24        3
248 2020-12-25    18040.0       505.0   193777.0  2020     12   25        4
249 2020-12-26    19037.0       459.0   152334.0  2020     12   26        5

[250 rows x 8 columns]

In [59]:
# Query the rows for May
covid_df_may = covid_df[covid_df.month == 5]

# Extract the subset of columns to be aggregated
covid_df_may_metrics = covid_df_may[['new_cases', 'new_deaths', 'new_tests']]

# Get the column-wise sum
covid_may_totals = covid_df_may_metrics.sum()

In [60]:
covid_may_totals

new_cases       29073.0
new_deaths       5658.0
new_tests     1913860.0
dtype: float64

In [61]:
type(covid_may_totals)

pandas.Series

In [62]:
covid_df[covid_df.month == 5][['new_cases', 'new_deaths', 'new_tests']].sum()

new_cases       29073.0
new_deaths       5658.0
new_tests     1913860.0
dtype: float64

In [63]:
covid_df.new_cases.mean()

np.float64(7411.428)

In [64]:
covid_df[covid_df.weekday == 6].new_cases.mean()

np.float64(8174.342857142857)