In [51]:
import pandas as pd
from urllib.request import urlretrieve

In [2]:
covid_df = pd.read_csv("files/covid_italy_250_days.csv")

In [3]:
type(covid_df)

pandas.DataFrame

In [4]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[250 rows x 4 columns]

In [5]:
covid_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        250 non-null    str
 1   new_cases   250 non-null    float64
 2   new_deaths  250 non-null    float64
 3   new_tests   250 non-null    float64
dtypes: float64(3), str(1)
memory usage: 7.9 KB

In [6]:
covid_df.describe()

          new_cases  new_deaths     new_tests
count    250.000000  250.000000     250.00000
mean    7411.428000  190.796000   98192.61200
std    11025.459118  248.686417   61905.97724
min      114.000000  -31.000000  -47510.00000
25%      340.000000   12.250000   52552.25000
50%     1399.000000   54.000000   72065.50000
75%    13177.500000  329.000000  142907.75000
max    40902.000000  993.000000  254908.00000

In [7]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

In [8]:
covid_df.shape

(250, 4)

In [9]:
covid_df['new_cases']

0       2256.0
1       2729.0
2       3370.0
3       2646.0
4       3021.0
        ...
245    10872.0
246    13318.0
247    14522.0
248    18040.0
249    19037.0
Name: new_cases, Length: 250, dtype: float64

In [10]:
covid_df['new_cases'][243]

np.float64(16308.0)

In [11]:
covid_df.at[246, 'new_cases']

np.float64(13318.0)

In [12]:
covid_df.new_cases

0       2256.0
1       2729.0
2       3370.0
3       2646.0
4       3021.0
        ...
245    10872.0
246    13318.0
247    14522.0
248    18040.0
249    19037.0
Name: new_cases, Length: 250, dtype: float64

In [13]:
covid_df[['new_cases', 'date']]

     new_cases        date
0       2256.0  2020-04-21
1       2729.0  2020-04-22
2       3370.0  2020-04-23
3       2646.0  2020-04-24
4       3021.0  2020-04-25
..         ...         ...
245    10872.0  2020-12-22
246    13318.0  2020-12-23
247    14522.0  2020-12-24
248    18040.0  2020-12-25
249    19037.0  2020-12-26

[250 rows x 2 columns]

In [14]:
covid_df_copy = covid_df.copy()

In [15]:
covid_df.loc[243]

date          2020-12-20
new_cases        16308.0
new_deaths         553.0
new_tests       176185.0
Name: 243, dtype: object

In [16]:
covid_df.head(3)

         date  new_cases  new_deaths  new_tests
0  2020-04-21     2256.0       454.0    41483.0
1  2020-04-22     2729.0       534.0    52126.0
2  2020-04-23     3370.0       437.0    63101.0

In [17]:
covid_df.new_tests.first_valid_index() # finding the first non empty

0

In [18]:
covid_df.loc[108:113]

           date  new_cases  new_deaths  new_tests
108  2020-08-07      402.0         6.0    58673.0
109  2020-08-08      552.0         3.0    59196.0
110  2020-08-09      347.0        13.0    53298.0
111  2020-08-10      463.0         2.0    37637.0
112  2020-08-11      259.0         4.0    26432.0
113  2020-08-12      412.0         6.0    40642.0

In [19]:
covid_df.sample(10)

           date  new_cases  new_deaths  new_tests
231  2020-12-08    13720.0       528.0   111217.0
114  2020-08-13      481.0        10.0    52658.0
51   2020-06-11      202.0        71.0    62699.0
24   2020-05-15      992.0       262.0    71876.0
194  2020-11-01    31758.0       297.0   215886.0
101  2020-07-31      386.0         3.0    61858.0
199  2020-11-06    34505.0       445.0   219884.0
76   2020-07-06      192.0         7.0    37462.0
26   2020-05-17      875.0       153.0    69179.0
204  2020-11-11    35098.0       580.0   217758.0

In [20]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()
print(total_cases)
print(total_deaths)

1852857.0
47699.0

In [21]:
death_rate = total_deaths / total_cases
print(death_rate)

0.025743486950153195

In [22]:
initial_tests = 935310
total_tests = initial_tests + covid_df.new_tests.sum()

In [23]:
total_tests

np.float64(25483463.0)

In [24]:
positive_rate = total_cases / total_tests
print(positive_rate)

0.07270821081106599

In [25]:
high_new_cases = covid_df.new_cases > 1000

In [26]:
high_new_cases

0      True
1      True
2      True
3      True
4      True
       ...
245    True
246    True
247    True
248    True
249    True
Name: new_cases, Length: 250, dtype: bool

In [27]:
covid_df[high_new_cases]

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[143 rows x 4 columns]

In [28]:
high_cases_df = covid_df[covid_df.new_cases > 1000]

In [29]:
high_cases_df

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[143 rows x 4 columns]

In [30]:
from IPython.display import display
with pd.option_context('display.max_rows', 100):
    display(covid_df[covid_df.new_cases > 1000])

           date  new_cases  new_deaths  new_tests
0    2020-04-21     2256.0       454.0    41483.0
1    2020-04-22     2729.0       534.0    52126.0
2    2020-04-23     3370.0       437.0    63101.0
3    2020-04-24     2646.0       464.0    66658.0
4    2020-04-25     3021.0       420.0    62447.0
..          ...        ...         ...        ...
245  2020-12-22    10872.0       415.0    87889.0
246  2020-12-23    13318.0       628.0   157705.0
247  2020-12-24    14522.0       553.0   183864.0
248  2020-12-25    18040.0       505.0   193777.0
249  2020-12-26    19037.0       459.0   152334.0

[143 rows x 4 columns]

In [31]:
covid_df['positive_rate'] = covid_df.new_cases / covid_df.new_tests

In [32]:
covid_df

           date  new_cases  new_deaths  new_tests  positive_rate
0    2020-04-21     2256.0       454.0    41483.0       0.054384
1    2020-04-22     2729.0       534.0    52126.0       0.052354
2    2020-04-23     3370.0       437.0    63101.0       0.053406
3    2020-04-24     2646.0       464.0    66658.0       0.039695
4    2020-04-25     3021.0       420.0    62447.0       0.048377
..          ...        ...         ...        ...            ...
245  2020-12-22    10872.0       415.0    87889.0       0.123701
246  2020-12-23    13318.0       628.0   157705.0       0.084449
247  2020-12-24    14522.0       553.0   183864.0       0.078982
248  2020-12-25    18040.0       505.0   193777.0       0.093097
249  2020-12-26    19037.0       459.0   152334.0       0.124969

[250 rows x 5 columns]

In [33]:
covid_df.drop(columns = ['positive_rate'], inplace=True)

In [34]:
covid_df.sort_values('new_cases', ascending=False).head(10)

           date  new_cases  new_deaths  new_tests
207  2020-11-14    40902.0       550.0   254908.0
201  2020-11-08    39811.0       425.0   231673.0
206  2020-11-13    37978.0       636.0   234672.0
200  2020-11-07    37809.0       446.0   234245.0
208  2020-11-15    37255.0       544.0   227695.0
214  2020-11-21    37242.0       699.0   238077.0
213  2020-11-20    36176.0       653.0   250186.0
204  2020-11-11    35098.0       580.0   217758.0
215  2020-11-22    34767.0       692.0   237225.0
199  2020-11-06    34505.0       445.0   219884.0

In [35]:
covid_df.sort_values('new_deaths', ascending=False).head(10)

           date  new_cases  new_deaths  new_tests
227  2020-12-04    23225.0       993.0   220047.0
234  2020-12-11    16999.0       887.0   171586.0
218  2020-11-25    23232.0       853.0   188659.0
239  2020-12-16    14844.0       846.0   164431.0
221  2020-11-28    28352.0       827.0   222803.0
220  2020-11-27    29003.0       822.0   232711.0
228  2020-12-05    24099.0       814.0   212741.0
225  2020-12-02    19350.0       785.0   182100.0
235  2020-12-12    18727.0       761.0   190416.0
212  2020-11-19    34282.0       753.0   234834.0

In [36]:
covid_df['date'] = pd.to_datetime(covid_df.date)

In [37]:
covid_df['date']

0     2020-04-21
1     2020-04-22
2     2020-04-23
3     2020-04-24
4     2020-04-25
         ...
245   2020-12-22
246   2020-12-23
247   2020-12-24
248   2020-12-25
249   2020-12-26
Name: date, Length: 250, dtype: datetime64[us]

In [38]:
covid_df['year'] = pd.DatetimeIndex(covid_df.date).year
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday

In [39]:
covid_df

          date  new_cases  new_deaths  new_tests  year  month  day  weekday
0   2020-04-21     2256.0       454.0    41483.0  2020      4   21        1
1   2020-04-22     2729.0       534.0    52126.0  2020      4   22        2
2   2020-04-23     3370.0       437.0    63101.0  2020      4   23        3
3   2020-04-24     2646.0       464.0    66658.0  2020      4   24        4
4   2020-04-25     3021.0       420.0    62447.0  2020      4   25        5
..         ...        ...         ...        ...   ...    ...  ...      ...
245 2020-12-22    10872.0       415.0    87889.0  2020     12   22        1
246 2020-12-23    13318.0       628.0   157705.0  2020     12   23        2
247 2020-12-24    14522.0       553.0   183864.0  2020     12   24        3
248 2020-12-25    18040.0       505.0   193777.0  2020     12   25        4
249 2020-12-26    19037.0       459.0   152334.0  2020     12   26        5

[250 rows x 8 columns]

In [40]:
# Query the rows for May
covid_df_may = covid_df[covid_df.month == 5]

# Extract the subset of columns to be aggregated
covid_df_may_metrics = covid_df_may[['new_cases', 'new_deaths', 'new_tests']]

# Get the column-wise sum
covid_may_totals = covid_df_may_metrics.sum()

In [41]:
covid_may_totals

new_cases       29073.0
new_deaths       5658.0
new_tests     1913860.0
dtype: float64

In [42]:
type(covid_may_totals)

pandas.Series

In [43]:
covid_df[covid_df.month == 5][['new_cases', 'new_deaths', 'new_tests']].sum()

new_cases       29073.0
new_deaths       5658.0
new_tests     1913860.0
dtype: float64

In [44]:
covid_df.new_cases.mean()

np.float64(7411.428)

In [45]:
covid_df[covid_df.weekday == 6].new_cases.mean()

np.float64(8174.342857142857)

In [47]:
grp = covid_df.groupby("month")[['new_cases', 'new_deaths', 'new_tests']].sum()
print(grp)

       new_cases  new_deaths  new_tests
month
4        24619.0      4022.0   554220.0
5        29073.0      5658.0  1913860.0
6         7797.0      1404.0  1517216.0
7         6769.0       388.0  1410332.0
8        21085.0       345.0  1834172.0
9        44768.0       398.0  2642017.0
10      334700.0      2446.0  4340217.0
11      937587.0     16583.0  6246000.0
12      446459.0     16455.0  4090119.0

In [48]:
covid_month_mean_df = covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].mean()
print(covid_month_mean_df)

          new_cases  new_deaths      new_tests
month
4       2461.900000  402.200000   55422.000000
5        937.838710  182.516129   61737.419355
6        259.900000   46.800000   50573.866667
7        218.354839   12.516129   45494.580645
8        680.161290   11.129032   59166.838710
9       1492.266667   13.266667   88067.233333
10     10796.774194   78.903226  140007.000000
11     31252.900000  552.766667  208200.000000
12     17171.500000  632.884615  157312.269231

In [49]:
covid_df['total_cases'] = covid_df.new_cases.cumsum()
covid_df['total_deaths'] = covid_df.new_deaths.cumsum()
covid_df['total_tests'] = covid_df.new_tests.cumsum() + initial_tests

In [50]:
covid_df

,date,new_cases,new_deaths,new_tests,year,month,day,weekday,total_cases,total_deaths,total_tests
0,2020-04-21,2256.0,454.0,41483.0,2020,4,21,1,2256.0,454.0,976793.0
1,2020-04-22,2729.0,534.0,52126.0,2020,4,22,2,4985.0,988.0,1028919.0
2,2020-04-23,3370.0,437.0,63101.0,2020,4,23,3,8355.0,1425.0,1092020.0
3,2020-04-24,2646.0,464.0,66658.0,2020,4,24,4,11001.0,1889.0,1158678.0
4,2020-04-25,3021.0,420.0,62447.0,2020,4,25,5,14022.0,2309.0,1221125.0
...,...,...,...,...,...,...,...,...,...,...,...
245,2020-12-22,10872.0,415.0,87889.0,2020,12,22,1,1787940.0,45554.0,24795783.0
246,2020-12-23,13318.0,628.0,157705.0,2020,12,23,2,1801258.0,46182.0,24953488.0
247,2020-12-24,14522.0,553.0,183864.0,2020,12,24,3,1815780.0,46735.0,25137352.0
248,2020-12-25,18040.0,505.0,193777.0,2020,12,25,4,1833820.0,47240.0,25331129.0
249,2020-12-26,19037.0,459.0,152334.0,2020,12,26,5,1852857.0,47699.0,25483463.0

In [52]:
urlretrieve('https://gist.githubusercontent.com/aakashns/8684589ef4f266116cdce023377fc9c8/raw/99ce3826b2a9d1e6d0bde7e9e559fc8b6e9ac88b/locations.csv',
            'files/locations.csv')

('files/locations.csv', <http.client.HTTPMessage at 0x218541447d0>)

In [53]:
locations_df = pd.read_csv('files/locations.csv')

In [54]:
locations_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,3.892834e+07,64.83,0.500,1803.987
1,Albania,Europe,2.877800e+06,78.57,2.890,11803.431
2,Algeria,Africa,4.385104e+07,76.88,1.900,13913.839
3,Andorra,Europe,7.726500e+04,83.73,NaN,NaN
4,Angola,Africa,3.286627e+07,61.15,NaN,5819.495
...,...,...,...,...,...,...
207,Yemen,Asia,2.982597e+07,66.12,0.700,1479.147
208,Zambia,Africa,1.838396e+07,63.89,2.000,3689.251
209,Zimbabwe,Africa,1.486293e+07,61.49,1.700,1899.775
210,World,NaN,7.794799e+09,72.58,2.705,15469.207
211,International,NaN,NaN,NaN,NaN,NaN

In [64]:
locations_df[locations_df.location == "Italy"]

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
97,Italy,Europe,60461828.0,83.51,3.18,35220.084

In [65]:
covid_df["location"] = "Italy"

In [66]:
covid_df

,date,new_cases,new_deaths,new_tests,year,month,day,weekday,total_cases,total_deaths,total_tests,location
0,2020-04-21,2256.0,454.0,41483.0,2020,4,21,1,2256.0,454.0,976793.0,Italy
1,2020-04-22,2729.0,534.0,52126.0,2020,4,22,2,4985.0,988.0,1028919.0,Italy
2,2020-04-23,3370.0,437.0,63101.0,2020,4,23,3,8355.0,1425.0,1092020.0,Italy
3,2020-04-24,2646.0,464.0,66658.0,2020,4,24,4,11001.0,1889.0,1158678.0,Italy
4,2020-04-25,3021.0,420.0,62447.0,2020,4,25,5,14022.0,2309.0,1221125.0,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...
245,2020-12-22,10872.0,415.0,87889.0,2020,12,22,1,1787940.0,45554.0,24795783.0,Italy
246,2020-12-23,13318.0,628.0,157705.0,2020,12,23,2,1801258.0,46182.0,24953488.0,Italy
247,2020-12-24,14522.0,553.0,183864.0,2020,12,24,3,1815780.0,46735.0,25137352.0,Italy
248,2020-12-25,18040.0,505.0,193777.0,2020,12,25,4,1833820.0,47240.0,25331129.0,Italy
249,2020-12-26,19037.0,459.0,152334.0,2020,12,26,5,1852857.0,47699.0,25483463.0,Italy

In [67]:
merged_df = covid_df.merge(locations_df, on="location")

In [68]:
merged_df

,date,new_cases,new_deaths,new_tests,year,month,day,weekday,total_cases,total_deaths,total_tests,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,2020-04-21,2256.0,454.0,41483.0,2020,4,21,1,2256.0,454.0,976793.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
1,2020-04-22,2729.0,534.0,52126.0,2020,4,22,2,4985.0,988.0,1028919.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
2,2020-04-23,3370.0,437.0,63101.0,2020,4,23,3,8355.0,1425.0,1092020.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
3,2020-04-24,2646.0,464.0,66658.0,2020,4,24,4,11001.0,1889.0,1158678.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
4,2020-04-25,3021.0,420.0,62447.0,2020,4,25,5,14022.0,2309.0,1221125.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2020-12-22,10872.0,415.0,87889.0,2020,12,22,1,1787940.0,45554.0,24795783.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
246,2020-12-23,13318.0,628.0,157705.0,2020,12,23,2,1801258.0,46182.0,24953488.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
247,2020-12-24,14522.0,553.0,183864.0,2020,12,24,3,1815780.0,46735.0,25137352.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
248,2020-12-25,18040.0,505.0,193777.0,2020,12,25,4,1833820.0,47240.0,25331129.0,Italy,Europe,60461828.0,83.51,3.18,35220.084
249,2020-12-26,19037.0,459.0,152334.0,2020,12,26,5,1852857.0,47699.0,25483463.0,Italy,Europe,60461828.0,83.51,3.18,35220.084

In [70]:
merged_df['cases_per_million'] = merged_df.total_cases * 1e6 / merged_df.population
merged_df['deaths_per_million'] = merged_df.total_deaths * 1e6 / merged_df.population
merged_df['tests_per_million'] = merged_df.total_tests * 1e6 / merged_df.population

In [71]:
result_df = merged_df[['date',
                       'new_cases',
                       'total_cases',
                       'new_deaths',
                       'total_deaths',
                       'new_tests',
                       'total_tests',
                       'cases_per_million',
                       'deaths_per_million',
                       'tests_per_million']]

In [72]:
result_df.to_csv('files/results.csv', index=None)